// Code generated by MockGen. DO NOT EDIT.
// Source: src/common/metrics/interfaces/api_request_metrics_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/common/metrics/interfaces/api_request_metrics_interface.go -destination=tests/common_mocks/metrics_mocks/interfaces_mocks/api_request_metrics_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockApiRequestMetricsInterface is a mock of ApiRequestMetricsInterface interface.
type MockApiRequestMetricsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockApiRequestMetricsInterfaceMockRecorder
	isgomock struct{}
}

// MockApiRequestMetricsInterfaceMockRecorder is the mock recorder for MockApiRequestMetricsInterface.
type MockApiRequestMetricsInterfaceMockRecorder struct {
	mock *MockApiRequestMetricsInterface
}

// NewMockApiRequestMetricsInterface creates a new mock instance.
func NewMockApiRequestMetricsInterface(ctrl *gomock.Controller) *MockApiRequestMetricsInterface {
	mock := &MockApiRequestMetricsInterface{ctrl: ctrl}
	mock.recorder = &MockApiRequestMetricsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiRequestMetricsInterface) EXPECT() *MockApiRequestMetricsInterfaceMockRecorder {
	return m.recorder
}

// DecActiveRequests mocks base method.
func (m *MockApiRequestMetricsInterface) DecActiveRequests(ctx context.Context, method string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DecActiveRequests", ctx, method)
}

// DecActiveRequests indicates an expected call of DecActiveRequests.
func (mr *MockApiRequestMetricsInterfaceMockRecorder) DecActiveRequests(ctx, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecActiveRequests", reflect.TypeOf((*MockApiRequestMetricsInterface)(nil).DecActiveRequests), ctx, method)
}

// IncActiveRequests mocks base method.
func (m *MockApiRequestMetricsInterface) IncActiveRequests(ctx context.Context, method string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncActiveRequests", ctx, method)
}

// IncActiveRequests indicates an expected call of IncActiveRequests.
func (mr *MockApiRequestMetricsInterfaceMockRecorder) IncActiveRequests(ctx, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncActiveRequests", reflect.TypeOf((*MockApiRequestMetricsInterface)(nil).IncActiveRequests), ctx, method)
}

// RecordRequest mocks base method.
func (m *MockApiRequestMetricsInterface) RecordRequest(ctx context.Context, method, route string, statusCode int, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRequest", ctx, method, route, statusCode, duration)
}

// RecordRequest indicates an expected call of RecordRequest.
func (mr *MockApiRequestMetricsInterfaceMockRecorder) RecordRequest(ctx, method, route, statusCode, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRequest", reflect.TypeOf((*MockApiRequestMetricsInterface)(nil).RecordRequest), ctx, method, route, statusCode, duration)
}
