// Code generated by MockGen. DO NOT EDIT.
// Source: src/common/metrics/interfaces/external_http_metrics_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/common/metrics/interfaces/external_http_metrics_interface.go -destination=tests/common_mocks/metrics_mocks/interfaces_mocks/external_http_metrics_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockExternalHttpMetricsInterface is a mock of ExternalHttpMetricsInterface interface.
type MockExternalHttpMetricsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockExternalHttpMetricsInterfaceMockRecorder
	isgomock struct{}
}

// MockExternalHttpMetricsInterfaceMockRecorder is the mock recorder for MockExternalHttpMetricsInterface.
type MockExternalHttpMetricsInterfaceMockRecorder struct {
	mock *MockExternalHttpMetricsInterface
}

// NewMockExternalHttpMetricsInterface creates a new mock instance.
func NewMockExternalHttpMetricsInterface(ctrl *gomock.Controller) *MockExternalHttpMetricsInterface {
	mock := &MockExternalHttpMetricsInterface{ctrl: ctrl}
	mock.recorder = &MockExternalHttpMetricsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalHttpMetricsInterface) EXPECT() *MockExternalHttpMetricsInterfaceMockRecorder {
	return m.recorder
}

// RecordRequest mocks base method.
func (m *MockExternalHttpMetricsInterface) RecordRequest(ctx context.Context, method, route string, statusCode int, duration time.Duration, responseSize int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRequest", ctx, method, route, statusCode, duration, responseSize)
}

// RecordRequest indicates an expected call of RecordRequest.
func (mr *MockExternalHttpMetricsInterfaceMockRecorder) RecordRequest(ctx, method, route, statusCode, duration, responseSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRequest", reflect.TypeOf((*MockExternalHttpMetricsInterface)(nil).RecordRequest), ctx, method, route, statusCode, duration, responseSize)
}

// RecordTransportError mocks base method.
func (m *MockExternalHttpMetricsInterface) RecordTransportError(ctx context.Context, method, route string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordTransportError", ctx, method, route, duration)
}

// RecordTransportError indicates an expected call of RecordTransportError.
func (mr *MockExternalHttpMetricsInterfaceMockRecorder) RecordTransportError(ctx, method, route, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordTransportError", reflect.TypeOf((*MockExternalHttpMetricsInterface)(nil).RecordTransportError), ctx, method, route, duration)
}
