// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/event_subscribers/agentic_ai_agent_collection_minted_event_subscriber_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/event_subscribers/agentic_ai_agent_collection_minted_event_subscriber_interface.go -destination=tests/pinata_bridge_mocks/event_subscribers_mocks/agenticai_agent_collection_minted_subscriber_mock.go -package=event_subscribers_mocks
//

// Package event_subscribers_mocks is a generated GoMock package.
package event_subscribers_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022protocol/agentic-ai-pinata-bridge/src/pinata_bridge/abi"
	ethereum "github.com/ethereum/go-ethereum"
	gomock "go.uber.org/mock/gomock"
)

// MockAgenticAIAgentCollectionMintedSubscriberInterface is a mock of AgenticAIAgentCollectionMintedSubscriberInterface interface.
type MockAgenticAIAgentCollectionMintedSubscriberInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgenticAIAgentCollectionMintedSubscriberInterfaceMockRecorder
	isgomock struct{}
}

// MockAgenticAIAgentCollectionMintedSubscriberInterfaceMockRecorder is the mock recorder for MockAgenticAIAgentCollectionMintedSubscriberInterface.
type MockAgenticAIAgentCollectionMintedSubscriberInterfaceMockRecorder struct {
	mock *MockAgenticAIAgentCollectionMintedSubscriberInterface
}

// NewMockAgenticAIAgentCollectionMintedSubscriberInterface creates a new mock instance.
func NewMockAgenticAIAgentCollectionMintedSubscriberInterface(ctrl *gomock.Controller) *MockAgenticAIAgentCollectionMintedSubscriberInterface {
	mock := &MockAgenticAIAgentCollectionMintedSubscriberInterface{ctrl: ctrl}
	mock.recorder = &MockAgenticAIAgentCollectionMintedSubscriberInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgenticAIAgentCollectionMintedSubscriberInterface) EXPECT() *MockAgenticAIAgentCollectionMintedSubscriberInterfaceMockRecorder {
	return m.recorder
}

// SubscribeMinted mocks base method.
func (m *MockAgenticAIAgentCollectionMintedSubscriberInterface) SubscribeMinted(ctx context.Context, logs chan<- *abi.AgenticAIAgentCollectionMinted) (ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeMinted", ctx, logs)
	ret0, _ := ret[0].(ethereum.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeMinted indicates an expected call of SubscribeMinted.
func (mr *MockAgenticAIAgentCollectionMintedSubscriberInterfaceMockRecorder) SubscribeMinted(ctx, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeMinted", reflect.TypeOf((*MockAgenticAIAgentCollectionMintedSubscriberInterface)(nil).SubscribeMinted), ctx, logs)
}
