// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge_listeners/chain_event_listener.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge_listeners/chain_event_listener.go -destination=tests/pinata_bridge_listeners_mocks/chain_event_mock.go -package=pinata_bridge_listeners_mocks
//

// Package pinata_bridge_listeners_mocks is a generated GoMock package.
package pinata_bridge_listeners_mocks

import (
	reflect "reflect"

	types "github.com/ethereum/go-ethereum/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockChainEvent is a mock of ChainEvent interface.
type MockChainEvent struct {
	ctrl     *gomock.Controller
	recorder *MockChainEventMockRecorder
	isgomock struct{}
}

// MockChainEventMockRecorder is the mock recorder for MockChainEvent.
type MockChainEventMockRecorder struct {
	mock *MockChainEvent
}

// NewMockChainEvent creates a new mock instance.
func NewMockChainEvent(ctrl *gomock.Controller) *MockChainEvent {
	mock := &MockChainEvent{ctrl: ctrl}
	mock.recorder = &MockChainEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainEvent) EXPECT() *MockChainEventMockRecorder {
	return m.recorder
}

// RawLog mocks base method.
func (m *MockChainEvent) RawLog() types.Log {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RawLog")
	ret0, _ := ret[0].(types.Log)
	return ret0
}

// RawLog indicates an expected call of RawLog.
func (mr *MockChainEventMockRecorder) RawLog() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RawLog", reflect.TypeOf((*MockChainEvent)(nil).RawLog))
}
