// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge_listeners/event_listener_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge_listeners/event_listener_interface.go -destination=tests/pinata_bridge_listeners_mocks/event_listener_mock.go -package=pinata_bridge_listeners_mocks
//

// Package pinata_bridge_listeners_mocks is a generated GoMock package.
package pinata_bridge_listeners_mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventListenerInterface is a mock of EventListenerInterface interface.
type MockEventListenerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockEventListenerInterfaceMockRecorder
	isgomock struct{}
}

// MockEventListenerInterfaceMockRecorder is the mock recorder for MockEventListenerInterface.
type MockEventListenerInterfaceMockRecorder struct {
	mock *MockEventListenerInterface
}

// NewMockEventListenerInterface creates a new mock instance.
func NewMockEventListenerInterface(ctrl *gomock.Controller) *MockEventListenerInterface {
	mock := &MockEventListenerInterface{ctrl: ctrl}
	mock.recorder = &MockEventListenerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventListenerInterface) EXPECT() *MockEventListenerInterfaceMockRecorder {
	return m.recorder
}

// Listen mocks base method.
func (m *MockEventListenerInterface) Listen(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Listen", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Listen indicates an expected call of Listen.
func (mr *MockEventListenerInterfaceMockRecorder) Listen(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockEventListenerInterface)(nil).Listen), ctx)
}

// SubscribeAll mocks base method.
func (m *MockEventListenerInterface) SubscribeAll(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeAll", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubscribeAll indicates an expected call of SubscribeAll.
func (mr *MockEventListenerInterfaceMockRecorder) SubscribeAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeAll", reflect.TypeOf((*MockEventListenerInterface)(nil).SubscribeAll), ctx)
}
