// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/use_cases/push_agent_image_cid_to_pinata.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/use_cases/push_agent_image_cid_to_pinata.go -destination=tests/pinata_bridge_mocks/use_cases_mocks/push_agent_image_cid_to_pinata_mock.go -package=use_cases_mocks
//

// Package use_cases_mocks is a generated GoMock package.
package use_cases_mocks

import (
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockPushAgentImageCidToPinataInterface is a mock of PushAgentImageCidToPinataInterface interface.
type MockPushAgentImageCidToPinataInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPushAgentImageCidToPinataInterfaceMockRecorder
	isgomock struct{}
}

// MockPushAgentImageCidToPinataInterfaceMockRecorder is the mock recorder for MockPushAgentImageCidToPinataInterface.
type MockPushAgentImageCidToPinataInterfaceMockRecorder struct {
	mock *MockPushAgentImageCidToPinataInterface
}

// NewMockPushAgentImageCidToPinataInterface creates a new mock instance.
func NewMockPushAgentImageCidToPinataInterface(ctrl *gomock.Controller) *MockPushAgentImageCidToPinataInterface {
	mock := &MockPushAgentImageCidToPinataInterface{ctrl: ctrl}
	mock.recorder = &MockPushAgentImageCidToPinataInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushAgentImageCidToPinataInterface) EXPECT() *MockPushAgentImageCidToPinataInterfaceMockRecorder {
	return m.recorder
}

// PushAllAgentImageCids mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushAllAgentImageCids() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushAllAgentImageCids")
	ret0, _ := ret[0].(error)
	return ret0
}

// PushAllAgentImageCids indicates an expected call of PushAllAgentImageCids.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushAllAgentImageCids() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushAllAgentImageCids", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushAllAgentImageCids))
}

// PushFromCid mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushFromCid(cid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushFromCid", cid)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushFromCid indicates an expected call of PushFromCid.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushFromCid(cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushFromCid", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushFromCid), cid)
}

// PushImageOfAgentImageProposal mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushImageOfAgentImageProposal(agentCollectionAddress common.Address, proposalId big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushImageOfAgentImageProposal", agentCollectionAddress, proposalId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushImageOfAgentImageProposal indicates an expected call of PushImageOfAgentImageProposal.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushImageOfAgentImageProposal(agentCollectionAddress, proposalId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushImageOfAgentImageProposal", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushImageOfAgentImageProposal), agentCollectionAddress, proposalId)
}

// PushImagesOfAgent mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushImagesOfAgent(agentCollectionAddress common.Address, agentCollectionTokenId big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushImagesOfAgent", agentCollectionAddress, agentCollectionTokenId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushImagesOfAgent indicates an expected call of PushImagesOfAgent.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushImagesOfAgent(agentCollectionAddress, agentCollectionTokenId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushImagesOfAgent", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushImagesOfAgent), agentCollectionAddress, agentCollectionTokenId)
}

// PushImagesOfMintProposal mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushImagesOfMintProposal(agentCollectionAddress common.Address, proposalId big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushImagesOfMintProposal", agentCollectionAddress, proposalId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushImagesOfMintProposal indicates an expected call of PushImagesOfMintProposal.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushImagesOfMintProposal(agentCollectionAddress, proposalId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushImagesOfMintProposal", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushImagesOfMintProposal), agentCollectionAddress, proposalId)
}
