// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/use_cases/push_agent_image_cid_to_pinata.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/use_cases/push_agent_image_cid_to_pinata.go -destination=tests/pinata_bridge_mocks/use_cases_mocks/push_agentmage_cid_to_pinata_mock.go -package=use_cases_mocks
//

// Package use_cases_mocks is a generated GoMock package.
package use_cases_mocks

import (
	big "math/big"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPushAgentImageCidToPinataInterface is a mock of PushAgentImageCidToPinataInterface interface.
type MockPushAgentImageCidToPinataInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPushAgentImageCidToPinataInterfaceMockRecorder
	isgomock struct{}
}

// MockPushAgentImageCidToPinataInterfaceMockRecorder is the mock recorder for MockPushAgentImageCidToPinataInterface.
type MockPushAgentImageCidToPinataInterfaceMockRecorder struct {
	mock *MockPushAgentImageCidToPinataInterface
}

// NewMockPushAgentImageCidToPinataInterface creates a new mock instance.
func NewMockPushAgentImageCidToPinataInterface(ctrl *gomock.Controller) *MockPushAgentImageCidToPinataInterface {
	mock := &MockPushAgentImageCidToPinataInterface{ctrl: ctrl}
	mock.recorder = &MockPushAgentImageCidToPinataInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushAgentImageCidToPinataInterface) EXPECT() *MockPushAgentImageCidToPinataInterfaceMockRecorder {
	return m.recorder
}

// PushFromAgentImageCid mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushFromAgentImageCid(cid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushFromAgentImageCid", cid)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushFromAgentImageCid indicates an expected call of PushFromAgentImageCid.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushFromAgentImageCid(cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushFromAgentImageCid", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushFromAgentImageCid), cid)
}

// PushFromAgentTokenId mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushFromAgentTokenId(tokenId big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushFromAgentTokenId", tokenId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushFromAgentTokenId indicates an expected call of PushFromAgentTokenId.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushFromAgentTokenId(tokenId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushFromAgentTokenId", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushFromAgentTokenId), tokenId)
}
