// Package clients provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package clients

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ListFilesParamsOrder.
const (
	ASC  ListFilesParamsOrder = "ASC"
	DESC ListFilesParamsOrder = "DESC"
)

// Defines values for ListFilesParamsNetwork.
const (
	Private ListFilesParamsNetwork = "private"
	Public  ListFilesParamsNetwork = "public"
)

// PinByCidJSONBody defines parameters for PinByCid.
type PinByCidJSONBody struct {
	// Cid CID of the file you want to pin
	Cid string `json:"cid"`

	// GroupId ID of the group you would like to upload
	GroupId *string `json:"group_id,omitempty"`

	// HostNodes An optional array of host node IDs, use `ipfs id` in Kubo to get these
	HostNodes *[]string `json:"host_nodes,omitempty"`

	// Keyvalues Add additional key value metadata to files upon upload
	Keyvalues *map[string]string `json:"keyvalues,omitempty"`

	// Name Add a custom name for the file
	Name *string `json:"name,omitempty"`
}

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	// Name Filter files by name
	Name *string `form:"name,omitempty" json:"name,omitempty"`

	// Group Filter fils by group_id. Pass `null` to show files that are not part of a group
	Group *string `form:"group,omitempty" json:"group,omitempty"`

	// MimeType Filter files by mime_type
	MimeType *string `form:"mimeType,omitempty" json:"mimeType,omitempty"`

	// Cid Filter files by CID
	Cid *string `form:"cid,omitempty" json:"cid,omitempty"`

	// CidPending Return only files that are still waiting for a CID
	CidPending *bool `form:"cidPending,omitempty" json:"cidPending,omitempty"`

	// Metadata Filter by key values in file metadata
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Limit Limit the number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Order Sort results by creation date with with ASC or DESC
	Order *ListFilesParamsOrder `form:"order,omitempty" json:"order,omitempty"`

	// PageToken Paginate using the nextPageToken
	PageToken *string `form:"pageToken,omitempty" json:"pageToken,omitempty"`
}

// ListFilesParamsOrder defines parameters for ListFiles.
type ListFilesParamsOrder string

// ListFilesParamsNetwork defines parameters for ListFiles.
type ListFilesParamsNetwork string

// PinByCidJSONRequestBody defines body for PinByCid for application/json ContentType.
type PinByCidJSONRequestBody PinByCidJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PinByCidWithBody request with any body
	PinByCidWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PinByCid(ctx context.Context, body PinByCidJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListFiles request
	ListFiles(ctx context.Context, network ListFilesParamsNetwork, params *ListFilesParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PinByCidWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPinByCidRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PinByCid(ctx context.Context, body PinByCidJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPinByCidRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListFiles(ctx context.Context, network ListFilesParamsNetwork, params *ListFilesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListFilesRequest(c.Server, network, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPinByCidRequest calls the generic PinByCid builder with application/json body
func NewPinByCidRequest(server string, body PinByCidJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPinByCidRequestWithBody(server, "application/json", bodyReader)
}

// NewPinByCidRequestWithBody generates requests for PinByCid with any type of body
func NewPinByCidRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/files/public/pin_by_cid")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListFilesRequest generates requests for ListFiles
func NewListFilesRequest(server string, network ListFilesParamsNetwork, params *ListFilesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "network", runtime.ParamLocationPath, network)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/files/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Name != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "name", runtime.ParamLocationQuery, *params.Name); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Group != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "group", runtime.ParamLocationQuery, *params.Group); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MimeType != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "mimeType", runtime.ParamLocationQuery, *params.MimeType); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Cid != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cid", runtime.ParamLocationQuery, *params.Cid); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.CidPending != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "cidPending", runtime.ParamLocationQuery, *params.CidPending); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Metadata != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("deepObject", true, "metadata", runtime.ParamLocationQuery, *params.Metadata); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Order != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "order", runtime.ParamLocationQuery, *params.Order); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "pageToken", runtime.ParamLocationQuery, *params.PageToken); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PinByCidWithBodyWithResponse request with any body
	PinByCidWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PinByCidResponse, error)

	PinByCidWithResponse(ctx context.Context, body PinByCidJSONRequestBody, reqEditors ...RequestEditorFn) (*PinByCidResponse, error)

	// ListFilesWithResponse request
	ListFilesWithResponse(ctx context.Context, network ListFilesParamsNetwork, params *ListFilesParams, reqEditors ...RequestEditorFn) (*ListFilesResponse, error)
}

type PinByCidResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *struct {
			Cid        *string                 `json:"cid,omitempty"`
			DateQueued *string                 `json:"date_queued,omitempty"`
			GroupId    *string                 `json:"group_id,omitempty"`
			HoseNodes  *[]string               `json:"hose_nodes,omitempty"`
			Id         *string                 `json:"id,omitempty"`
			Keyvalues  *map[string]interface{} `json:"keyvalues,omitempty"`
			Name       *string                 `json:"name,omitempty"`
			Status     *string                 `json:"status,omitempty"`
		} `json:"data,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PinByCidResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PinByCidResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListFilesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Data *struct {
			Files *[]struct {
				Cid           *string                 `json:"cid,omitempty"`
				CreatedAt     *string                 `json:"created_at,omitempty"`
				GroupId       *string                 `json:"group_id,omitempty"`
				Id            *string                 `json:"id,omitempty"`
				Keyvalues     *map[string]interface{} `json:"keyvalues,omitempty"`
				MimeType      *string                 `json:"mime_type,omitempty"`
				Name          *string                 `json:"name,omitempty"`
				NumberOfFiles *float32                `json:"number_of_files,omitempty"`
				Size          *float32                `json:"size,omitempty"`
			} `json:"files,omitempty"`
			NextPageToken *string `json:"next_page_token,omitempty"`
		} `json:"data,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r ListFilesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListFilesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PinByCidWithBodyWithResponse request with arbitrary body returning *PinByCidResponse
func (c *ClientWithResponses) PinByCidWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PinByCidResponse, error) {
	rsp, err := c.PinByCidWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePinByCidResponse(rsp)
}

func (c *ClientWithResponses) PinByCidWithResponse(ctx context.Context, body PinByCidJSONRequestBody, reqEditors ...RequestEditorFn) (*PinByCidResponse, error) {
	rsp, err := c.PinByCid(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePinByCidResponse(rsp)
}

// ListFilesWithResponse request returning *ListFilesResponse
func (c *ClientWithResponses) ListFilesWithResponse(ctx context.Context, network ListFilesParamsNetwork, params *ListFilesParams, reqEditors ...RequestEditorFn) (*ListFilesResponse, error) {
	rsp, err := c.ListFiles(ctx, network, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListFilesResponse(rsp)
}

// ParsePinByCidResponse parses an HTTP response from a PinByCidWithResponse call
func ParsePinByCidResponse(rsp *http.Response) (*PinByCidResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PinByCidResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *struct {
				Cid        *string                 `json:"cid,omitempty"`
				DateQueued *string                 `json:"date_queued,omitempty"`
				GroupId    *string                 `json:"group_id,omitempty"`
				HoseNodes  *[]string               `json:"hose_nodes,omitempty"`
				Id         *string                 `json:"id,omitempty"`
				Keyvalues  *map[string]interface{} `json:"keyvalues,omitempty"`
				Name       *string                 `json:"name,omitempty"`
				Status     *string                 `json:"status,omitempty"`
			} `json:"data,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListFilesResponse parses an HTTP response from a ListFilesWithResponse call
func ParseListFilesResponse(rsp *http.Response) (*ListFilesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListFilesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Data *struct {
				Files *[]struct {
					Cid           *string                 `json:"cid,omitempty"`
					CreatedAt     *string                 `json:"created_at,omitempty"`
					GroupId       *string                 `json:"group_id,omitempty"`
					Id            *string                 `json:"id,omitempty"`
					Keyvalues     *map[string]interface{} `json:"keyvalues,omitempty"`
					MimeType      *string                 `json:"mime_type,omitempty"`
					Name          *string                 `json:"name,omitempty"`
					NumberOfFiles *float32                `json:"number_of_files,omitempty"`
					Size          *float32                `json:"size,omitempty"`
				} `json:"files,omitempty"`
				NextPageToken *string `json:"next_page_token,omitempty"`
			} `json:"data,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
