// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/event_handlers/agent_image_proposal_created_handler.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/event_handlers/agent_image_proposal_created_handler.go -destination=tests/pinata_bridge_mocks/event_handlers_mocks/agent_image_proposal_created_event_handler_mock.go -package=event_handlers_mocks
//

// Package event_handlers_mocks is a generated GoMock package.
package event_handlers_mocks

import (
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/abi"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentImageProposalCreatedEventHandlerInterface is a mock of AgentImageProposalCreatedEventHandlerInterface interface.
type MockAgentImageProposalCreatedEventHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentImageProposalCreatedEventHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentImageProposalCreatedEventHandlerInterfaceMockRecorder is the mock recorder for MockAgentImageProposalCreatedEventHandlerInterface.
type MockAgentImageProposalCreatedEventHandlerInterfaceMockRecorder struct {
	mock *MockAgentImageProposalCreatedEventHandlerInterface
}

// NewMockAgentImageProposalCreatedEventHandlerInterface creates a new mock instance.
func NewMockAgentImageProposalCreatedEventHandlerInterface(ctrl *gomock.Controller) *MockAgentImageProposalCreatedEventHandlerInterface {
	mock := &MockAgentImageProposalCreatedEventHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockAgentImageProposalCreatedEventHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentImageProposalCreatedEventHandlerInterface) EXPECT() *MockAgentImageProposalCreatedEventHandlerInterfaceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockAgentImageProposalCreatedEventHandlerInterface) Handle(chainId uint64, event *abi.AgentCollectionV1AgentImageProposalCreated) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", chainId, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockAgentImageProposalCreatedEventHandlerInterfaceMockRecorder) Handle(chainId, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockAgentImageProposalCreatedEventHandlerInterface)(nil).Handle), chainId, event)
}
