// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/event_handlers/mint_proposal_created_event_handler.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/event_handlers/mint_proposal_created_event_handler.go -destination=tests/pinata_bridge_mocks/event_handlers_mocks/mint_proposal_created_event_handler_mock.go -package=event_handlers_mocks
//

// Package event_handlers_mocks is a generated GoMock package.
package event_handlers_mocks

import (
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/abi"
	gomock "go.uber.org/mock/gomock"
)

// MockMintProposalCreatedEventHandlerInterface is a mock of MintProposalCreatedEventHandlerInterface interface.
type MockMintProposalCreatedEventHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMintProposalCreatedEventHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockMintProposalCreatedEventHandlerInterfaceMockRecorder is the mock recorder for MockMintProposalCreatedEventHandlerInterface.
type MockMintProposalCreatedEventHandlerInterfaceMockRecorder struct {
	mock *MockMintProposalCreatedEventHandlerInterface
}

// NewMockMintProposalCreatedEventHandlerInterface creates a new mock instance.
func NewMockMintProposalCreatedEventHandlerInterface(ctrl *gomock.Controller) *MockMintProposalCreatedEventHandlerInterface {
	mock := &MockMintProposalCreatedEventHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockMintProposalCreatedEventHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMintProposalCreatedEventHandlerInterface) EXPECT() *MockMintProposalCreatedEventHandlerInterfaceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockMintProposalCreatedEventHandlerInterface) Handle(event *abi.AgentCollectionV1MintProposalCreated) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockMintProposalCreatedEventHandlerInterfaceMockRecorder) Handle(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockMintProposalCreatedEventHandlerInterface)(nil).Handle), event)
}
