// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge_http_ipfs_check/clients/ipfs_check_client.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge_http_ipfs_check/clients/ipfs_check_client.go -destination=tests/pinata_bridge_http_ipfs_check_mocks/clients_mocks/ipfs_check_client_mock.go -package=clients_mocks
//

// Package clients_mocks is a generated GoMock package.
package clients_mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge_http_ipfs_check/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIpfsCheckClientInterface is a mock of IpfsCheckClientInterface interface.
type MockIpfsCheckClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIpfsCheckClientInterfaceMockRecorder
	isgomock struct{}
}

// MockIpfsCheckClientInterfaceMockRecorder is the mock recorder for MockIpfsCheckClientInterface.
type MockIpfsCheckClientInterfaceMockRecorder struct {
	mock *MockIpfsCheckClientInterface
}

// NewMockIpfsCheckClientInterface creates a new mock instance.
func NewMockIpfsCheckClientInterface(ctrl *gomock.Controller) *MockIpfsCheckClientInterface {
	mock := &MockIpfsCheckClientInterface{ctrl: ctrl}
	mock.recorder = &MockIpfsCheckClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpfsCheckClientInterface) EXPECT() *MockIpfsCheckClientInterfaceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockIpfsCheckClientInterface) Check(ctx context.Context, cid string) ([]models.ExternalCheckResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, cid)
	ret0, _ := ret[0].([]models.ExternalCheckResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Check indicates an expected call of Check.
func (mr *MockIpfsCheckClientInterfaceMockRecorder) Check(ctx, cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockIpfsCheckClientInterface)(nil).Check), ctx, cid)
}
