// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge_listeners/metrics/interfaces/chain_event_metrics_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge_listeners/metrics/interfaces/chain_event_metrics_interface.go -destination=tests/pinata_bridge_listeners_mocks/metrics_mocks/interfaces_mocks/chain_event_metrics_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockChainEventMetricsInterface is a mock of ChainEventMetricsInterface interface.
type MockChainEventMetricsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChainEventMetricsInterfaceMockRecorder
	isgomock struct{}
}

// MockChainEventMetricsInterfaceMockRecorder is the mock recorder for MockChainEventMetricsInterface.
type MockChainEventMetricsInterfaceMockRecorder struct {
	mock *MockChainEventMetricsInterface
}

// NewMockChainEventMetricsInterface creates a new mock instance.
func NewMockChainEventMetricsInterface(ctrl *gomock.Controller) *MockChainEventMetricsInterface {
	mock := &MockChainEventMetricsInterface{ctrl: ctrl}
	mock.recorder = &MockChainEventMetricsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainEventMetricsInterface) EXPECT() *MockChainEventMetricsInterfaceMockRecorder {
	return m.recorder
}

// RecordEvent mocks base method.
func (m *MockChainEventMetricsInterface) RecordEvent(ctx context.Context, eventName string, chainId uint64, outcome string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordEvent", ctx, eventName, chainId, outcome, duration)
}

// RecordEvent indicates an expected call of RecordEvent.
func (mr *MockChainEventMetricsInterfaceMockRecorder) RecordEvent(ctx, eventName, chainId, outcome, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordEvent", reflect.TypeOf((*MockChainEventMetricsInterface)(nil).RecordEvent), ctx, eventName, chainId, outcome, duration)
}

// RecordSubscriptionClosed mocks base method.
func (m *MockChainEventMetricsInterface) RecordSubscriptionClosed(ctx context.Context, eventName string, chainId uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordSubscriptionClosed", ctx, eventName, chainId)
}

// RecordSubscriptionClosed indicates an expected call of RecordSubscriptionClosed.
func (mr *MockChainEventMetricsInterfaceMockRecorder) RecordSubscriptionClosed(ctx, eventName, chainId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSubscriptionClosed", reflect.TypeOf((*MockChainEventMetricsInterface)(nil).RecordSubscriptionClosed), ctx, eventName, chainId)
}

// RecordSubscriptionError mocks base method.
func (m *MockChainEventMetricsInterface) RecordSubscriptionError(ctx context.Context, eventName string, chainId uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordSubscriptionError", ctx, eventName, chainId)
}

// RecordSubscriptionError indicates an expected call of RecordSubscriptionError.
func (mr *MockChainEventMetricsInterfaceMockRecorder) RecordSubscriptionError(ctx, eventName, chainId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSubscriptionError", reflect.TypeOf((*MockChainEventMetricsInterface)(nil).RecordSubscriptionError), ctx, eventName, chainId)
}

// RecordSubscriptionOpened mocks base method.
func (m *MockChainEventMetricsInterface) RecordSubscriptionOpened(ctx context.Context, eventName string, chainId uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordSubscriptionOpened", ctx, eventName, chainId)
}

// RecordSubscriptionOpened indicates an expected call of RecordSubscriptionOpened.
func (mr *MockChainEventMetricsInterfaceMockRecorder) RecordSubscriptionOpened(ctx, eventName, chainId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSubscriptionOpened", reflect.TypeOf((*MockChainEventMetricsInterface)(nil).RecordSubscriptionOpened), ctx, eventName, chainId)
}
