// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/metrics/interfaces/pin_metrics_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/metrics/interfaces/pin_metrics_interface.go -destination=tests/pinata_bridge_mocks/metrics_mocks/interfaces_mocks/pin_metrics_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPinMetricsInterface is a mock of PinMetricsInterface interface.
type MockPinMetricsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPinMetricsInterfaceMockRecorder
	isgomock struct{}
}

// MockPinMetricsInterfaceMockRecorder is the mock recorder for MockPinMetricsInterface.
type MockPinMetricsInterfaceMockRecorder struct {
	mock *MockPinMetricsInterface
}

// NewMockPinMetricsInterface creates a new mock instance.
func NewMockPinMetricsInterface(ctrl *gomock.Controller) *MockPinMetricsInterface {
	mock := &MockPinMetricsInterface{ctrl: ctrl}
	mock.recorder = &MockPinMetricsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinMetricsInterface) EXPECT() *MockPinMetricsInterfaceMockRecorder {
	return m.recorder
}

// RecordHostLookup mocks base method.
func (m *MockPinMetricsInterface) RecordHostLookup(ctx context.Context, outcome string, attempts int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordHostLookup", ctx, outcome, attempts)
}

// RecordHostLookup indicates an expected call of RecordHostLookup.
func (mr *MockPinMetricsInterfaceMockRecorder) RecordHostLookup(ctx, outcome, attempts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHostLookup", reflect.TypeOf((*MockPinMetricsInterface)(nil).RecordHostLookup), ctx, outcome, attempts)
}

// RecordPin mocks base method.
func (m *MockPinMetricsInterface) RecordPin(ctx context.Context, outcome string, withHostAddresses bool, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordPin", ctx, outcome, withHostAddresses, duration)
}

// RecordPin indicates an expected call of RecordPin.
func (mr *MockPinMetricsInterfaceMockRecorder) RecordPin(ctx, outcome, withHostAddresses, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordPin", reflect.TypeOf((*MockPinMetricsInterface)(nil).RecordPin), ctx, outcome, withHostAddresses, duration)
}

// RecordSweep mocks base method.
func (m *MockPinMetricsInterface) RecordSweep(ctx context.Context, kind string, duration time.Duration, failed bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordSweep", ctx, kind, duration, failed)
}

// RecordSweep indicates an expected call of RecordSweep.
func (mr *MockPinMetricsInterfaceMockRecorder) RecordSweep(ctx, kind, duration, failed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSweep", reflect.TypeOf((*MockPinMetricsInterface)(nil).RecordSweep), ctx, kind, duration, failed)
}

// RecordSweepImage mocks base method.
func (m *MockPinMetricsInterface) RecordSweepImage(ctx context.Context, kind, outcome string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordSweepImage", ctx, kind, outcome)
}

// RecordSweepImage indicates an expected call of RecordSweepImage.
func (mr *MockPinMetricsInterfaceMockRecorder) RecordSweepImage(ctx, kind, outcome any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSweepImage", reflect.TypeOf((*MockPinMetricsInterface)(nil).RecordSweepImage), ctx, kind, outcome)
}
