// Code generated by MockGen. DO NOT EDIT.
// Source: src/common/mvc/interfaces/controller_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/common/mvc/interfaces/controller_interface.go -destination=tests/common_mocks/mvc_mocks/interfaces_mocks/controller_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	fiber "github.com/gofiber/fiber/v3"
	gomock "go.uber.org/mock/gomock"
)

// MockControllerInterface is a mock of ControllerInterface interface.
type MockControllerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockControllerInterfaceMockRecorder
	isgomock struct{}
}

// MockControllerInterfaceMockRecorder is the mock recorder for MockControllerInterface.
type MockControllerInterfaceMockRecorder struct {
	mock *MockControllerInterface
}

// NewMockControllerInterface creates a new mock instance.
func NewMockControllerInterface(ctrl *gomock.Controller) *MockControllerInterface {
	mock := &MockControllerInterface{ctrl: ctrl}
	mock.recorder = &MockControllerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockControllerInterface) EXPECT() *MockControllerInterfaceMockRecorder {
	return m.recorder
}

// RegisterRoutes mocks base method.
func (m *MockControllerInterface) RegisterRoutes(app fiber.Router) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterRoutes", app)
}

// RegisterRoutes indicates an expected call of RegisterRoutes.
func (mr *MockControllerInterfaceMockRecorder) RegisterRoutes(app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterRoutes", reflect.TypeOf((*MockControllerInterface)(nil).RegisterRoutes), app)
}
