// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge_http_pinata/clients/oapi_client.gen.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge_http_pinata/clients/oapi_client.gen.go -destination=tests/pinata_bridge_http_pinata_mocks/clients_mocks/client_with_responses_mock.go -package=clients_mocks
//

// Package clients_mocks is a generated GoMock package.
package clients_mocks

import (
	context "context"
	io "io"
	http "net/http"
	reflect "reflect"

	clients "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge_http_pinata/clients"
	gomock "go.uber.org/mock/gomock"
)

// MockHttpRequestDoer is a mock of HttpRequestDoer interface.
type MockHttpRequestDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHttpRequestDoerMockRecorder
	isgomock struct{}
}

// MockHttpRequestDoerMockRecorder is the mock recorder for MockHttpRequestDoer.
type MockHttpRequestDoerMockRecorder struct {
	mock *MockHttpRequestDoer
}

// NewMockHttpRequestDoer creates a new mock instance.
func NewMockHttpRequestDoer(ctrl *gomock.Controller) *MockHttpRequestDoer {
	mock := &MockHttpRequestDoer{ctrl: ctrl}
	mock.recorder = &MockHttpRequestDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpRequestDoer) EXPECT() *MockHttpRequestDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHttpRequestDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHttpRequestDoerMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHttpRequestDoer)(nil).Do), req)
}

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
	isgomock struct{}
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// ListFiles mocks base method.
func (m *MockClientInterface) ListFiles(ctx context.Context, network clients.ListFilesParamsNetwork, params *clients.ListFilesParams, reqEditors ...clients.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, network, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFiles", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFiles indicates an expected call of ListFiles.
func (mr *MockClientInterfaceMockRecorder) ListFiles(ctx, network, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, network, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFiles", reflect.TypeOf((*MockClientInterface)(nil).ListFiles), varargs...)
}

// PinByCid mocks base method.
func (m *MockClientInterface) PinByCid(ctx context.Context, body clients.PinByCidJSONRequestBody, reqEditors ...clients.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PinByCid", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PinByCid indicates an expected call of PinByCid.
func (mr *MockClientInterfaceMockRecorder) PinByCid(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinByCid", reflect.TypeOf((*MockClientInterface)(nil).PinByCid), varargs...)
}

// PinByCidWithBody mocks base method.
func (m *MockClientInterface) PinByCidWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...clients.RequestEditorFn) (*http.Response, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PinByCidWithBody", varargs...)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PinByCidWithBody indicates an expected call of PinByCidWithBody.
func (mr *MockClientInterfaceMockRecorder) PinByCidWithBody(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinByCidWithBody", reflect.TypeOf((*MockClientInterface)(nil).PinByCidWithBody), varargs...)
}

// MockClientWithResponsesInterface is a mock of ClientWithResponsesInterface interface.
type MockClientWithResponsesInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientWithResponsesInterfaceMockRecorder
	isgomock struct{}
}

// MockClientWithResponsesInterfaceMockRecorder is the mock recorder for MockClientWithResponsesInterface.
type MockClientWithResponsesInterfaceMockRecorder struct {
	mock *MockClientWithResponsesInterface
}

// NewMockClientWithResponsesInterface creates a new mock instance.
func NewMockClientWithResponsesInterface(ctrl *gomock.Controller) *MockClientWithResponsesInterface {
	mock := &MockClientWithResponsesInterface{ctrl: ctrl}
	mock.recorder = &MockClientWithResponsesInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientWithResponsesInterface) EXPECT() *MockClientWithResponsesInterfaceMockRecorder {
	return m.recorder
}

// ListFilesWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) ListFilesWithResponse(ctx context.Context, network clients.ListFilesParamsNetwork, params *clients.ListFilesParams, reqEditors ...clients.RequestEditorFn) (*clients.ListFilesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, network, params}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListFilesWithResponse", varargs...)
	ret0, _ := ret[0].(*clients.ListFilesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFilesWithResponse indicates an expected call of ListFilesWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) ListFilesWithResponse(ctx, network, params any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, network, params}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFilesWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).ListFilesWithResponse), varargs...)
}

// PinByCidWithBodyWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PinByCidWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...clients.RequestEditorFn) (*clients.PinByCidResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, contentType, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PinByCidWithBodyWithResponse", varargs...)
	ret0, _ := ret[0].(*clients.PinByCidResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PinByCidWithBodyWithResponse indicates an expected call of PinByCidWithBodyWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PinByCidWithBodyWithResponse(ctx, contentType, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, contentType, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinByCidWithBodyWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PinByCidWithBodyWithResponse), varargs...)
}

// PinByCidWithResponse mocks base method.
func (m *MockClientWithResponsesInterface) PinByCidWithResponse(ctx context.Context, body clients.PinByCidJSONRequestBody, reqEditors ...clients.RequestEditorFn) (*clients.PinByCidResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, body}
	for _, a := range reqEditors {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PinByCidWithResponse", varargs...)
	ret0, _ := ret[0].(*clients.PinByCidResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PinByCidWithResponse indicates an expected call of PinByCidWithResponse.
func (mr *MockClientWithResponsesInterfaceMockRecorder) PinByCidWithResponse(ctx, body any, reqEditors ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, body}, reqEditors...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinByCidWithResponse", reflect.TypeOf((*MockClientWithResponsesInterface)(nil).PinByCidWithResponse), varargs...)
}
