// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge_http_pinata/clients/pinata_client.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge_http_pinata/clients/pinata_client.go -destination=tests/pinata_bridge_http_pinata_mocks/clients_mocks/pinata_client_mock.go -package=clients_mocks
//

// Package clients_mocks is a generated GoMock package.
package clients_mocks

import (
	reflect "reflect"

	models "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge_http_pinata/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPinataClientInterface is a mock of PinataClientInterface interface.
type MockPinataClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPinataClientInterfaceMockRecorder
	isgomock struct{}
}

// MockPinataClientInterfaceMockRecorder is the mock recorder for MockPinataClientInterface.
type MockPinataClientInterfaceMockRecorder struct {
	mock *MockPinataClientInterface
}

// NewMockPinataClientInterface creates a new mock instance.
func NewMockPinataClientInterface(ctrl *gomock.Controller) *MockPinataClientInterface {
	mock := &MockPinataClientInterface{ctrl: ctrl}
	mock.recorder = &MockPinataClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinataClientInterface) EXPECT() *MockPinataClientInterfaceMockRecorder {
	return m.recorder
}

// PinByHash mocks base method.
func (m *MockPinataClientInterface) PinByHash(request *models.ExternalPinByHashRequest) (*models.ExternalPinByHashResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PinByHash", request)
	ret0, _ := ret[0].(*models.ExternalPinByHashResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PinByHash indicates an expected call of PinByHash.
func (mr *MockPinataClientInterfaceMockRecorder) PinByHash(request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinByHash", reflect.TypeOf((*MockPinataClientInterface)(nil).PinByHash), request)
}

// QueryFileByCid mocks base method.
func (m *MockPinataClientInterface) QueryFileByCid(cid string) (*models.ExternalQueryFilesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryFileByCid", cid)
	ret0, _ := ret[0].(*models.ExternalQueryFilesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryFileByCid indicates an expected call of QueryFileByCid.
func (mr *MockPinataClientInterfaceMockRecorder) QueryFileByCid(cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryFileByCid", reflect.TypeOf((*MockPinataClientInterface)(nil).QueryFileByCid), cid)
}
