// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/subscribers/agent_collection_mint_proposal_created_event_subscriber_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/subscribers/agent_collection_mint_proposal_created_event_subscriber_interface.go -destination=tests/pinata_bridge_mocks/subscribers_mocks/agent_collection_mint_proposal_created_subscriber_mock.go -package=subscribers_mocks
//

// Package subscribers_mocks is a generated GoMock package.
package subscribers_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/abi"
	ethereum "github.com/ethereum/go-ethereum"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCollectionMintProposalCreatedSubscriberInterface is a mock of AgentCollectionMintProposalCreatedSubscriberInterface interface.
type MockAgentCollectionMintProposalCreatedSubscriberInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCollectionMintProposalCreatedSubscriberInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentCollectionMintProposalCreatedSubscriberInterfaceMockRecorder is the mock recorder for MockAgentCollectionMintProposalCreatedSubscriberInterface.
type MockAgentCollectionMintProposalCreatedSubscriberInterfaceMockRecorder struct {
	mock *MockAgentCollectionMintProposalCreatedSubscriberInterface
}

// NewMockAgentCollectionMintProposalCreatedSubscriberInterface creates a new mock instance.
func NewMockAgentCollectionMintProposalCreatedSubscriberInterface(ctrl *gomock.Controller) *MockAgentCollectionMintProposalCreatedSubscriberInterface {
	mock := &MockAgentCollectionMintProposalCreatedSubscriberInterface{ctrl: ctrl}
	mock.recorder = &MockAgentCollectionMintProposalCreatedSubscriberInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCollectionMintProposalCreatedSubscriberInterface) EXPECT() *MockAgentCollectionMintProposalCreatedSubscriberInterfaceMockRecorder {
	return m.recorder
}

// SubscribeMintProposalCreated mocks base method.
func (m *MockAgentCollectionMintProposalCreatedSubscriberInterface) SubscribeMintProposalCreated(ctx context.Context, chainId uint64, agentCollectionAddress common.Address, logs chan<- *abi.AgentCollectionV1MintProposalCreated) (ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeMintProposalCreated", ctx, chainId, agentCollectionAddress, logs)
	ret0, _ := ret[0].(ethereum.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeMintProposalCreated indicates an expected call of SubscribeMintProposalCreated.
func (mr *MockAgentCollectionMintProposalCreatedSubscriberInterfaceMockRecorder) SubscribeMintProposalCreated(ctx, chainId, agentCollectionAddress, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeMintProposalCreated", reflect.TypeOf((*MockAgentCollectionMintProposalCreatedSubscriberInterface)(nil).SubscribeMintProposalCreated), ctx, chainId, agentCollectionAddress, logs)
}
