// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/subscribers/agent_collection_agent_image_proposal_created_event_subscriber_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/subscribers/agent_collection_agent_image_proposal_created_event_subscriber_interface.go -destination=tests/pinata_bridge_mocks/subscribers_mocks/agent_collection_agent_image_proposal_created_subscriber_mock.go -package=subscribers_mocks
//

// Package subscribers_mocks is a generated GoMock package.
package subscribers_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/abi"
	ethereum "github.com/ethereum/go-ethereum"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCollectionAgentImageProposalCreatedSubscriberInterface is a mock of AgentCollectionAgentImageProposalCreatedSubscriberInterface interface.
type MockAgentCollectionAgentImageProposalCreatedSubscriberInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCollectionAgentImageProposalCreatedSubscriberInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentCollectionAgentImageProposalCreatedSubscriberInterfaceMockRecorder is the mock recorder for MockAgentCollectionAgentImageProposalCreatedSubscriberInterface.
type MockAgentCollectionAgentImageProposalCreatedSubscriberInterfaceMockRecorder struct {
	mock *MockAgentCollectionAgentImageProposalCreatedSubscriberInterface
}

// NewMockAgentCollectionAgentImageProposalCreatedSubscriberInterface creates a new mock instance.
func NewMockAgentCollectionAgentImageProposalCreatedSubscriberInterface(ctrl *gomock.Controller) *MockAgentCollectionAgentImageProposalCreatedSubscriberInterface {
	mock := &MockAgentCollectionAgentImageProposalCreatedSubscriberInterface{ctrl: ctrl}
	mock.recorder = &MockAgentCollectionAgentImageProposalCreatedSubscriberInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCollectionAgentImageProposalCreatedSubscriberInterface) EXPECT() *MockAgentCollectionAgentImageProposalCreatedSubscriberInterfaceMockRecorder {
	return m.recorder
}

// SubscribeAgentImageProposalCreated mocks base method.
func (m *MockAgentCollectionAgentImageProposalCreatedSubscriberInterface) SubscribeAgentImageProposalCreated(ctx context.Context, chainId uint64, agentCollectionAddress common.Address, logs chan<- *abi.AgentCollectionV1AgentImageProposalCreated) (ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeAgentImageProposalCreated", ctx, chainId, agentCollectionAddress, logs)
	ret0, _ := ret[0].(ethereum.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeAgentImageProposalCreated indicates an expected call of SubscribeAgentImageProposalCreated.
func (mr *MockAgentCollectionAgentImageProposalCreatedSubscriberInterfaceMockRecorder) SubscribeAgentImageProposalCreated(ctx, chainId, agentCollectionAddress, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeAgentImageProposalCreated", reflect.TypeOf((*MockAgentCollectionAgentImageProposalCreatedSubscriberInterface)(nil).SubscribeAgentImageProposalCreated), ctx, chainId, agentCollectionAddress, logs)
}
