// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/subscribers/agent_collection_minted_event_subscriber_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/subscribers/agent_collection_minted_event_subscriber_interface.go -destination=tests/pinata_bridge_mocks/subscribers_mocks/agent_collection_minted_subscriber_mock.go -package=subscribers_mocks
//

// Package subscribers_mocks is a generated GoMock package.
package subscribers_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/abi"
	ethereum "github.com/ethereum/go-ethereum"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCollectionMintedSubscriberInterface is a mock of AgentCollectionMintedSubscriberInterface interface.
type MockAgentCollectionMintedSubscriberInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCollectionMintedSubscriberInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentCollectionMintedSubscriberInterfaceMockRecorder is the mock recorder for MockAgentCollectionMintedSubscriberInterface.
type MockAgentCollectionMintedSubscriberInterfaceMockRecorder struct {
	mock *MockAgentCollectionMintedSubscriberInterface
}

// NewMockAgentCollectionMintedSubscriberInterface creates a new mock instance.
func NewMockAgentCollectionMintedSubscriberInterface(ctrl *gomock.Controller) *MockAgentCollectionMintedSubscriberInterface {
	mock := &MockAgentCollectionMintedSubscriberInterface{ctrl: ctrl}
	mock.recorder = &MockAgentCollectionMintedSubscriberInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCollectionMintedSubscriberInterface) EXPECT() *MockAgentCollectionMintedSubscriberInterfaceMockRecorder {
	return m.recorder
}

// SubscribeMinted mocks base method.
func (m *MockAgentCollectionMintedSubscriberInterface) SubscribeMinted(ctx context.Context, chainId uint64, agentCollectionAddress common.Address, logs chan<- *abi.AgentCollectionV1Minted) (ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeMinted", ctx, chainId, agentCollectionAddress, logs)
	ret0, _ := ret[0].(ethereum.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeMinted indicates an expected call of SubscribeMinted.
func (mr *MockAgentCollectionMintedSubscriberInterfaceMockRecorder) SubscribeMinted(ctx, chainId, agentCollectionAddress, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeMinted", reflect.TypeOf((*MockAgentCollectionMintedSubscriberInterface)(nil).SubscribeMinted), ctx, chainId, agentCollectionAddress, logs)
}
