// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/subscribers/agent_collections_manager_collection_created_subscriber_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/subscribers/agent_collections_manager_collection_created_subscriber_interface.go -destination=tests/pinata_bridge_mocks/subscribers_mocks/agent_collections_manager_collection_created_subscriber_mock.go -package=subscribers_mocks
//

// Package subscribers_mocks is a generated GoMock package.
package subscribers_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/abi"
	ethereum "github.com/ethereum/go-ethereum"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCollectionsManagerCollectionCreatedSubscriberInterface is a mock of AgentCollectionsManagerCollectionCreatedSubscriberInterface interface.
type MockAgentCollectionsManagerCollectionCreatedSubscriberInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCollectionsManagerCollectionCreatedSubscriberInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentCollectionsManagerCollectionCreatedSubscriberInterfaceMockRecorder is the mock recorder for MockAgentCollectionsManagerCollectionCreatedSubscriberInterface.
type MockAgentCollectionsManagerCollectionCreatedSubscriberInterfaceMockRecorder struct {
	mock *MockAgentCollectionsManagerCollectionCreatedSubscriberInterface
}

// NewMockAgentCollectionsManagerCollectionCreatedSubscriberInterface creates a new mock instance.
func NewMockAgentCollectionsManagerCollectionCreatedSubscriberInterface(ctrl *gomock.Controller) *MockAgentCollectionsManagerCollectionCreatedSubscriberInterface {
	mock := &MockAgentCollectionsManagerCollectionCreatedSubscriberInterface{ctrl: ctrl}
	mock.recorder = &MockAgentCollectionsManagerCollectionCreatedSubscriberInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCollectionsManagerCollectionCreatedSubscriberInterface) EXPECT() *MockAgentCollectionsManagerCollectionCreatedSubscriberInterfaceMockRecorder {
	return m.recorder
}

// SubscribeCollectionCreated mocks base method.
func (m *MockAgentCollectionsManagerCollectionCreatedSubscriberInterface) SubscribeCollectionCreated(ctx context.Context, chainId uint64, logs chan<- *abi.AgentCollectionsManagerCollectionCreated) (ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubscribeCollectionCreated", ctx, chainId, logs)
	ret0, _ := ret[0].(ethereum.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeCollectionCreated indicates an expected call of SubscribeCollectionCreated.
func (mr *MockAgentCollectionsManagerCollectionCreatedSubscriberInterfaceMockRecorder) SubscribeCollectionCreated(ctx, chainId, logs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeCollectionCreated", reflect.TypeOf((*MockAgentCollectionsManagerCollectionCreatedSubscriberInterface)(nil).SubscribeCollectionCreated), ctx, chainId, logs)
}
