// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/traces/interfaces/pin_tracer_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/traces/interfaces/pin_tracer_interface.go -destination=tests/pinata_bridge_mocks/traces_mocks/interfaces_mocks/pin_tracer_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"

	interfaces "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/traces/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockPinTracerInterface is a mock of PinTracerInterface interface.
type MockPinTracerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPinTracerInterfaceMockRecorder
	isgomock struct{}
}

// MockPinTracerInterfaceMockRecorder is the mock recorder for MockPinTracerInterface.
type MockPinTracerInterfaceMockRecorder struct {
	mock *MockPinTracerInterface
}

// NewMockPinTracerInterface creates a new mock instance.
func NewMockPinTracerInterface(ctrl *gomock.Controller) *MockPinTracerInterface {
	mock := &MockPinTracerInterface{ctrl: ctrl}
	mock.recorder = &MockPinTracerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinTracerInterface) EXPECT() *MockPinTracerInterfaceMockRecorder {
	return m.recorder
}

// StartPin mocks base method.
func (m *MockPinTracerInterface) StartPin(ctx context.Context, cid string) (context.Context, interfaces.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartPin", ctx, cid)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(interfaces.Span)
	return ret0, ret1
}

// StartPin indicates an expected call of StartPin.
func (mr *MockPinTracerInterfaceMockRecorder) StartPin(ctx, cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartPin", reflect.TypeOf((*MockPinTracerInterface)(nil).StartPin), ctx, cid)
}

// StartSweep mocks base method.
func (m *MockPinTracerInterface) StartSweep(ctx context.Context, kind string) (context.Context, interfaces.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSweep", ctx, kind)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(interfaces.Span)
	return ret0, ret1
}

// StartSweep indicates an expected call of StartSweep.
func (mr *MockPinTracerInterfaceMockRecorder) StartSweep(ctx, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSweep", reflect.TypeOf((*MockPinTracerInterface)(nil).StartSweep), ctx, kind)
}
