// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/agent_collection_requester_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/agent_collection_requester_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/agent_collection_requester_mock.go -package=services_mocks
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCollectionRequesterInterface is a mock of AgentCollectionRequesterInterface interface.
type MockAgentCollectionRequesterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCollectionRequesterInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentCollectionRequesterInterfaceMockRecorder is the mock recorder for MockAgentCollectionRequesterInterface.
type MockAgentCollectionRequesterInterfaceMockRecorder struct {
	mock *MockAgentCollectionRequesterInterface
}

// NewMockAgentCollectionRequesterInterface creates a new mock instance.
func NewMockAgentCollectionRequesterInterface(ctrl *gomock.Controller) *MockAgentCollectionRequesterInterface {
	mock := &MockAgentCollectionRequesterInterface{ctrl: ctrl}
	mock.recorder = &MockAgentCollectionRequesterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCollectionRequesterInterface) EXPECT() *MockAgentCollectionRequesterInterfaceMockRecorder {
	return m.recorder
}

// GetAgentImageProposalImage mocks base method.
func (m *MockAgentCollectionRequesterInterface) GetAgentImageProposalImage(collectionAddress common.Address, proposalId big.Int) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentImageProposalImage", collectionAddress, proposalId)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentImageProposalImage indicates an expected call of GetAgentImageProposalImage.
func (mr *MockAgentCollectionRequesterInterfaceMockRecorder) GetAgentImageProposalImage(collectionAddress, proposalId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentImageProposalImage", reflect.TypeOf((*MockAgentCollectionRequesterInterface)(nil).GetAgentImageProposalImage), collectionAddress, proposalId)
}

// GetAgentImages mocks base method.
func (m *MockAgentCollectionRequesterInterface) GetAgentImages(collectionAddress common.Address, agentTokenId big.Int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentImages", collectionAddress, agentTokenId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentImages indicates an expected call of GetAgentImages.
func (mr *MockAgentCollectionRequesterInterfaceMockRecorder) GetAgentImages(collectionAddress, agentTokenId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentImages", reflect.TypeOf((*MockAgentCollectionRequesterInterface)(nil).GetAgentImages), collectionAddress, agentTokenId)
}

// GetAllTokenIds mocks base method.
func (m *MockAgentCollectionRequesterInterface) GetAllTokenIds(collectionAddress common.Address) ([]big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTokenIds", collectionAddress)
	ret0, _ := ret[0].([]big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTokenIds indicates an expected call of GetAllTokenIds.
func (mr *MockAgentCollectionRequesterInterfaceMockRecorder) GetAllTokenIds(collectionAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTokenIds", reflect.TypeOf((*MockAgentCollectionRequesterInterface)(nil).GetAllTokenIds), collectionAddress)
}

// GetMintProposalImages mocks base method.
func (m *MockAgentCollectionRequesterInterface) GetMintProposalImages(collectionAddress common.Address, proposalId big.Int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMintProposalImages", collectionAddress, proposalId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMintProposalImages indicates an expected call of GetMintProposalImages.
func (mr *MockAgentCollectionRequesterInterfaceMockRecorder) GetMintProposalImages(collectionAddress, proposalId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMintProposalImages", reflect.TypeOf((*MockAgentCollectionRequesterInterface)(nil).GetMintProposalImages), collectionAddress, proposalId)
}
