// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/agentic_ai_agent_collection_requester_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/agentic_ai_agent_collection_requester_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/agenticai_agent_collection_requester_mock.go -package=services_mocks
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	big "math/big"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAgenticAIAgentCollectionRequesterInterface is a mock of AgenticAIAgentCollectionRequesterInterface interface.
type MockAgenticAIAgentCollectionRequesterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgenticAIAgentCollectionRequesterInterfaceMockRecorder
	isgomock struct{}
}

// MockAgenticAIAgentCollectionRequesterInterfaceMockRecorder is the mock recorder for MockAgenticAIAgentCollectionRequesterInterface.
type MockAgenticAIAgentCollectionRequesterInterfaceMockRecorder struct {
	mock *MockAgenticAIAgentCollectionRequesterInterface
}

// NewMockAgenticAIAgentCollectionRequesterInterface creates a new mock instance.
func NewMockAgenticAIAgentCollectionRequesterInterface(ctrl *gomock.Controller) *MockAgenticAIAgentCollectionRequesterInterface {
	mock := &MockAgenticAIAgentCollectionRequesterInterface{ctrl: ctrl}
	mock.recorder = &MockAgenticAIAgentCollectionRequesterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgenticAIAgentCollectionRequesterInterface) EXPECT() *MockAgenticAIAgentCollectionRequesterInterfaceMockRecorder {
	return m.recorder
}

// GetAgentImage mocks base method.
func (m *MockAgenticAIAgentCollectionRequesterInterface) GetAgentImage(agentTokenId big.Int) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentImage", agentTokenId)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentImage indicates an expected call of GetAgentImage.
func (mr *MockAgenticAIAgentCollectionRequesterInterfaceMockRecorder) GetAgentImage(agentTokenId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentImage", reflect.TypeOf((*MockAgenticAIAgentCollectionRequesterInterface)(nil).GetAgentImage), agentTokenId)
}
