// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/pinata_requester_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/pinata_requester_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/pinata_requester_mock.go -package=services_mocks
//

// Package services_mocks is a generated GoMock package.
package services_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPinataRequesterInterface is a mock of PinataRequesterInterface interface.
type MockPinataRequesterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPinataRequesterInterfaceMockRecorder
	isgomock struct{}
}

// MockPinataRequesterInterfaceMockRecorder is the mock recorder for MockPinataRequesterInterface.
type MockPinataRequesterInterfaceMockRecorder struct {
	mock *MockPinataRequesterInterface
}

// NewMockPinataRequesterInterface creates a new mock instance.
func NewMockPinataRequesterInterface(ctrl *gomock.Controller) *MockPinataRequesterInterface {
	mock := &MockPinataRequesterInterface{ctrl: ctrl}
	mock.recorder = &MockPinataRequesterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinataRequesterInterface) EXPECT() *MockPinataRequesterInterfaceMockRecorder {
	return m.recorder
}

// PinCidToPinata mocks base method.
func (m *MockPinataRequesterInterface) PinCidToPinata(cid string, hostNodes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PinCidToPinata", cid, hostNodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// PinCidToPinata indicates an expected call of PinCidToPinata.
func (mr *MockPinataRequesterInterfaceMockRecorder) PinCidToPinata(cid, hostNodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinCidToPinata", reflect.TypeOf((*MockPinataRequesterInterface)(nil).PinCidToPinata), cid, hostNodes)
}
