// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge_blockchain/metrics/interfaces/blockchain_rpc_metrics_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge_blockchain/metrics/interfaces/blockchain_rpc_metrics_interface.go -destination=tests/pinata_bridge_blockchain_mocks/metrics_mocks/interfaces_mocks/blockchain_rpc_metrics_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockBlockchainRpcMetricsInterface is a mock of BlockchainRpcMetricsInterface interface.
type MockBlockchainRpcMetricsInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBlockchainRpcMetricsInterfaceMockRecorder
	isgomock struct{}
}

// MockBlockchainRpcMetricsInterfaceMockRecorder is the mock recorder for MockBlockchainRpcMetricsInterface.
type MockBlockchainRpcMetricsInterfaceMockRecorder struct {
	mock *MockBlockchainRpcMetricsInterface
}

// NewMockBlockchainRpcMetricsInterface creates a new mock instance.
func NewMockBlockchainRpcMetricsInterface(ctrl *gomock.Controller) *MockBlockchainRpcMetricsInterface {
	mock := &MockBlockchainRpcMetricsInterface{ctrl: ctrl}
	mock.recorder = &MockBlockchainRpcMetricsInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockchainRpcMetricsInterface) EXPECT() *MockBlockchainRpcMetricsInterfaceMockRecorder {
	return m.recorder
}

// RecordRequest mocks base method.
func (m *MockBlockchainRpcMetricsInterface) RecordRequest(ctx context.Context, chainID string, duration time.Duration, failed bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordRequest", ctx, chainID, duration, failed)
}

// RecordRequest indicates an expected call of RecordRequest.
func (mr *MockBlockchainRpcMetricsInterfaceMockRecorder) RecordRequest(ctx, chainID, duration, failed any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRequest", reflect.TypeOf((*MockBlockchainRpcMetricsInterface)(nil).RecordRequest), ctx, chainID, duration, failed)
}
