// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/agent_collection_mint_proposal_created_event_subscription_provider_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/agent_collection_mint_proposal_created_event_subscription_provider_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/agent_collection_mint_proposal_created_event_subscription_provider_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/abi"
	ethereum "github.com/ethereum/go-ethereum"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterface is a mock of AgentCollectionMintProposalCreatedEventSubscriptionProviderInterface interface.
type MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterfaceMockRecorder is the mock recorder for MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterface.
type MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterfaceMockRecorder struct {
	mock *MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterface
}

// NewMockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterface creates a new mock instance.
func NewMockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterface(ctrl *gomock.Controller) *MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterface {
	mock := &MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterface{ctrl: ctrl}
	mock.recorder = &MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterface) EXPECT() *MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterfaceMockRecorder {
	return m.recorder
}

// StartMintProposalCreatedSubscription mocks base method.
func (m *MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterface) StartMintProposalCreatedSubscription(chainId uint64, agentCollectionAddress common.Address) (<-chan *abi.AgentCollectionV1MintProposalCreated, ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMintProposalCreatedSubscription", chainId, agentCollectionAddress)
	ret0, _ := ret[0].(<-chan *abi.AgentCollectionV1MintProposalCreated)
	ret1, _ := ret[1].(ethereum.Subscription)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StartMintProposalCreatedSubscription indicates an expected call of StartMintProposalCreatedSubscription.
func (mr *MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterfaceMockRecorder) StartMintProposalCreatedSubscription(chainId, agentCollectionAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMintProposalCreatedSubscription", reflect.TypeOf((*MockAgentCollectionMintProposalCreatedEventSubscriptionProviderInterface)(nil).StartMintProposalCreatedSubscription), chainId, agentCollectionAddress)
}
