// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/agent_collection_minted_event_subscription_provider_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/agent_collection_minted_event_subscription_provider_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/agent_collection_minted_event_subscription_provider_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/abi"
	ethereum "github.com/ethereum/go-ethereum"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCollectionMintedEventSubscriptionProviderInterface is a mock of AgentCollectionMintedEventSubscriptionProviderInterface interface.
type MockAgentCollectionMintedEventSubscriptionProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCollectionMintedEventSubscriptionProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentCollectionMintedEventSubscriptionProviderInterfaceMockRecorder is the mock recorder for MockAgentCollectionMintedEventSubscriptionProviderInterface.
type MockAgentCollectionMintedEventSubscriptionProviderInterfaceMockRecorder struct {
	mock *MockAgentCollectionMintedEventSubscriptionProviderInterface
}

// NewMockAgentCollectionMintedEventSubscriptionProviderInterface creates a new mock instance.
func NewMockAgentCollectionMintedEventSubscriptionProviderInterface(ctrl *gomock.Controller) *MockAgentCollectionMintedEventSubscriptionProviderInterface {
	mock := &MockAgentCollectionMintedEventSubscriptionProviderInterface{ctrl: ctrl}
	mock.recorder = &MockAgentCollectionMintedEventSubscriptionProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCollectionMintedEventSubscriptionProviderInterface) EXPECT() *MockAgentCollectionMintedEventSubscriptionProviderInterfaceMockRecorder {
	return m.recorder
}

// StartMintedSubscription mocks base method.
func (m *MockAgentCollectionMintedEventSubscriptionProviderInterface) StartMintedSubscription(chainId uint64, agentCollectionAddress common.Address) (<-chan *abi.AgentCollectionV1Minted, ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMintedSubscription", chainId, agentCollectionAddress)
	ret0, _ := ret[0].(<-chan *abi.AgentCollectionV1Minted)
	ret1, _ := ret[1].(ethereum.Subscription)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StartMintedSubscription indicates an expected call of StartMintedSubscription.
func (mr *MockAgentCollectionMintedEventSubscriptionProviderInterfaceMockRecorder) StartMintedSubscription(chainId, agentCollectionAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMintedSubscription", reflect.TypeOf((*MockAgentCollectionMintedEventSubscriptionProviderInterface)(nil).StartMintedSubscription), chainId, agentCollectionAddress)
}
