// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/agent_image_updated_event_handler_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/agent_image_updated_event_handler_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/agent_image_updated_event_handler_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/abi"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentImageUpdatedEventHandlerInterface is a mock of AgentImageUpdatedEventHandlerInterface interface.
type MockAgentImageUpdatedEventHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentImageUpdatedEventHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentImageUpdatedEventHandlerInterfaceMockRecorder is the mock recorder for MockAgentImageUpdatedEventHandlerInterface.
type MockAgentImageUpdatedEventHandlerInterfaceMockRecorder struct {
	mock *MockAgentImageUpdatedEventHandlerInterface
}

// NewMockAgentImageUpdatedEventHandlerInterface creates a new mock instance.
func NewMockAgentImageUpdatedEventHandlerInterface(ctrl *gomock.Controller) *MockAgentImageUpdatedEventHandlerInterface {
	mock := &MockAgentImageUpdatedEventHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockAgentImageUpdatedEventHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentImageUpdatedEventHandlerInterface) EXPECT() *MockAgentImageUpdatedEventHandlerInterfaceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockAgentImageUpdatedEventHandlerInterface) Handle(ctx context.Context, chainId uint64, event *abi.AgentCollectionV1AgentImageUpdated) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, chainId, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockAgentImageUpdatedEventHandlerInterfaceMockRecorder) Handle(ctx, chainId, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockAgentImageUpdatedEventHandlerInterface)(nil).Handle), ctx, chainId, event)
}
