// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/agent_images_pinner_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/agent_images_pinner_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/agent_images_pinner_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentImagesPinnerInterface is a mock of AgentImagesPinnerInterface interface.
type MockAgentImagesPinnerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentImagesPinnerInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentImagesPinnerInterfaceMockRecorder is the mock recorder for MockAgentImagesPinnerInterface.
type MockAgentImagesPinnerInterfaceMockRecorder struct {
	mock *MockAgentImagesPinnerInterface
}

// NewMockAgentImagesPinnerInterface creates a new mock instance.
func NewMockAgentImagesPinnerInterface(ctrl *gomock.Controller) *MockAgentImagesPinnerInterface {
	mock := &MockAgentImagesPinnerInterface{ctrl: ctrl}
	mock.recorder = &MockAgentImagesPinnerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentImagesPinnerInterface) EXPECT() *MockAgentImagesPinnerInterfaceMockRecorder {
	return m.recorder
}

// PinMissing mocks base method.
func (m *MockAgentImagesPinnerInterface) PinMissing(ctx context.Context, chainId uint64, agentCollectionAddress common.Address, tokenId big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PinMissing", ctx, chainId, agentCollectionAddress, tokenId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PinMissing indicates an expected call of PinMissing.
func (mr *MockAgentImagesPinnerInterfaceMockRecorder) PinMissing(ctx, chainId, agentCollectionAddress, tokenId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinMissing", reflect.TypeOf((*MockAgentImagesPinnerInterface)(nil).PinMissing), ctx, chainId, agentCollectionAddress, tokenId)
}
