// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/agent_image_proposal_image_pinner_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/agent_image_proposal_image_pinner_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/agent_image_proposal_image_pinner_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentImageProposalImagePinnerInterface is a mock of AgentImageProposalImagePinnerInterface interface.
type MockAgentImageProposalImagePinnerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentImageProposalImagePinnerInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentImageProposalImagePinnerInterfaceMockRecorder is the mock recorder for MockAgentImageProposalImagePinnerInterface.
type MockAgentImageProposalImagePinnerInterfaceMockRecorder struct {
	mock *MockAgentImageProposalImagePinnerInterface
}

// NewMockAgentImageProposalImagePinnerInterface creates a new mock instance.
func NewMockAgentImageProposalImagePinnerInterface(ctrl *gomock.Controller) *MockAgentImageProposalImagePinnerInterface {
	mock := &MockAgentImageProposalImagePinnerInterface{ctrl: ctrl}
	mock.recorder = &MockAgentImageProposalImagePinnerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentImageProposalImagePinnerInterface) EXPECT() *MockAgentImageProposalImagePinnerInterfaceMockRecorder {
	return m.recorder
}

// Pin mocks base method.
func (m *MockAgentImageProposalImagePinnerInterface) Pin(ctx context.Context, chainId uint64, agentCollectionAddress common.Address, proposalId big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pin", ctx, chainId, agentCollectionAddress, proposalId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pin indicates an expected call of Pin.
func (mr *MockAgentImageProposalImagePinnerInterfaceMockRecorder) Pin(ctx, chainId, agentCollectionAddress, proposalId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pin", reflect.TypeOf((*MockAgentImageProposalImagePinnerInterface)(nil).Pin), ctx, chainId, agentCollectionAddress, proposalId)
}
