// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/agent_collections_manager_requester_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/agent_collections_manager_requester_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/agent_collections_manager_requester_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCollectionsManagerRequesterInterface is a mock of AgentCollectionsManagerRequesterInterface interface.
type MockAgentCollectionsManagerRequesterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCollectionsManagerRequesterInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentCollectionsManagerRequesterInterfaceMockRecorder is the mock recorder for MockAgentCollectionsManagerRequesterInterface.
type MockAgentCollectionsManagerRequesterInterfaceMockRecorder struct {
	mock *MockAgentCollectionsManagerRequesterInterface
}

// NewMockAgentCollectionsManagerRequesterInterface creates a new mock instance.
func NewMockAgentCollectionsManagerRequesterInterface(ctrl *gomock.Controller) *MockAgentCollectionsManagerRequesterInterface {
	mock := &MockAgentCollectionsManagerRequesterInterface{ctrl: ctrl}
	mock.recorder = &MockAgentCollectionsManagerRequesterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCollectionsManagerRequesterInterface) EXPECT() *MockAgentCollectionsManagerRequesterInterfaceMockRecorder {
	return m.recorder
}

// GetAllCollectionAddresses mocks base method.
func (m *MockAgentCollectionsManagerRequesterInterface) GetAllCollectionAddresses(chainId uint64) ([]common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCollectionAddresses", chainId)
	ret0, _ := ret[0].([]common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCollectionAddresses indicates an expected call of GetAllCollectionAddresses.
func (mr *MockAgentCollectionsManagerRequesterInterfaceMockRecorder) GetAllCollectionAddresses(chainId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCollectionAddresses", reflect.TypeOf((*MockAgentCollectionsManagerRequesterInterface)(nil).GetAllCollectionAddresses), chainId)
}
