// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/agent_image_updated_subscription_provider_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/agent_image_updated_subscription_provider_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/agent_image_updated_subscription_provider_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/abi"
	ethereum "github.com/ethereum/go-ethereum"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentImageUpdatedSubscriptionProviderInterface is a mock of AgentImageUpdatedSubscriptionProviderInterface interface.
type MockAgentImageUpdatedSubscriptionProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentImageUpdatedSubscriptionProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentImageUpdatedSubscriptionProviderInterfaceMockRecorder is the mock recorder for MockAgentImageUpdatedSubscriptionProviderInterface.
type MockAgentImageUpdatedSubscriptionProviderInterfaceMockRecorder struct {
	mock *MockAgentImageUpdatedSubscriptionProviderInterface
}

// NewMockAgentImageUpdatedSubscriptionProviderInterface creates a new mock instance.
func NewMockAgentImageUpdatedSubscriptionProviderInterface(ctrl *gomock.Controller) *MockAgentImageUpdatedSubscriptionProviderInterface {
	mock := &MockAgentImageUpdatedSubscriptionProviderInterface{ctrl: ctrl}
	mock.recorder = &MockAgentImageUpdatedSubscriptionProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentImageUpdatedSubscriptionProviderInterface) EXPECT() *MockAgentImageUpdatedSubscriptionProviderInterfaceMockRecorder {
	return m.recorder
}

// StartAgentImageUpdatedSubscription mocks base method.
func (m *MockAgentImageUpdatedSubscriptionProviderInterface) StartAgentImageUpdatedSubscription(ctx context.Context, chainId uint64, agentCollectionAddresses []common.Address) (<-chan *abi.AgentCollectionV1AgentImageUpdated, ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartAgentImageUpdatedSubscription", ctx, chainId, agentCollectionAddresses)
	ret0, _ := ret[0].(<-chan *abi.AgentCollectionV1AgentImageUpdated)
	ret1, _ := ret[1].(ethereum.Subscription)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StartAgentImageUpdatedSubscription indicates an expected call of StartAgentImageUpdatedSubscription.
func (mr *MockAgentImageUpdatedSubscriptionProviderInterfaceMockRecorder) StartAgentImageUpdatedSubscription(ctx, chainId, agentCollectionAddresses any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartAgentImageUpdatedSubscription", reflect.TypeOf((*MockAgentImageUpdatedSubscriptionProviderInterface)(nil).StartAgentImageUpdatedSubscription), ctx, chainId, agentCollectionAddresses)
}
