// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/agent_collection_agent_image_proposal_created_event_subscription_provider_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/agent_collection_agent_image_proposal_created_event_subscription_provider_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/agent_collection_agent_image_proposal_created_event_subscription_provider_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge_blockchain/abi"
	ethereum "github.com/ethereum/go-ethereum"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface is a mock of AgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface interface.
type MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterfaceMockRecorder is the mock recorder for MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface.
type MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterfaceMockRecorder struct {
	mock *MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface
}

// NewMockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface creates a new mock instance.
func NewMockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface(ctrl *gomock.Controller) *MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface {
	mock := &MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface{ctrl: ctrl}
	mock.recorder = &MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface) EXPECT() *MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterfaceMockRecorder {
	return m.recorder
}

// StartAgentImageProposalCreatedSubscription mocks base method.
func (m *MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface) StartAgentImageProposalCreatedSubscription(ctx context.Context, chainId uint64, agentCollectionAddress common.Address) (<-chan *abi.AgentCollectionV1AgentImageProposalCreated, ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartAgentImageProposalCreatedSubscription", ctx, chainId, agentCollectionAddress)
	ret0, _ := ret[0].(<-chan *abi.AgentCollectionV1AgentImageProposalCreated)
	ret1, _ := ret[1].(ethereum.Subscription)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StartAgentImageProposalCreatedSubscription indicates an expected call of StartAgentImageProposalCreatedSubscription.
func (mr *MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterfaceMockRecorder) StartAgentImageProposalCreatedSubscription(ctx, chainId, agentCollectionAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartAgentImageProposalCreatedSubscription", reflect.TypeOf((*MockAgentCollectionAgentImageProposalCreatedEventSubscriptionProviderInterface)(nil).StartAgentImageProposalCreatedSubscription), ctx, chainId, agentCollectionAddress)
}
