// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/agent_collections_manager_collection_created_event_subscription_provider_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/agent_collections_manager_collection_created_event_subscription_provider_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/agent_collections_manager_collection_created_event_subscription_provider_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge/abi"
	ethereum "github.com/ethereum/go-ethereum"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface is a mock of AgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface interface.
type MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterfaceMockRecorder is the mock recorder for MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface.
type MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterfaceMockRecorder struct {
	mock *MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface
}

// NewMockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface creates a new mock instance.
func NewMockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface(ctrl *gomock.Controller) *MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface {
	mock := &MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface{ctrl: ctrl}
	mock.recorder = &MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface) EXPECT() *MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterfaceMockRecorder {
	return m.recorder
}

// StartCollectionCreatedSubscription mocks base method.
func (m *MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface) StartCollectionCreatedSubscription(ctx context.Context, chainId uint64) (<-chan *abi.AgentCollectionsManagerCollectionCreated, ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCollectionCreatedSubscription", ctx, chainId)
	ret0, _ := ret[0].(<-chan *abi.AgentCollectionsManagerCollectionCreated)
	ret1, _ := ret[1].(ethereum.Subscription)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StartCollectionCreatedSubscription indicates an expected call of StartCollectionCreatedSubscription.
func (mr *MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterfaceMockRecorder) StartCollectionCreatedSubscription(ctx, chainId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCollectionCreatedSubscription", reflect.TypeOf((*MockAgentCollectionsManagerCollectionCreatedEventSubscriptionProviderInterface)(nil).StartCollectionCreatedSubscription), ctx, chainId)
}
