// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/cid_pinner_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/cid_pinner_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/cid_pinner_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCidPinnerInterface is a mock of CidPinnerInterface interface.
type MockCidPinnerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCidPinnerInterfaceMockRecorder
	isgomock struct{}
}

// MockCidPinnerInterfaceMockRecorder is the mock recorder for MockCidPinnerInterface.
type MockCidPinnerInterfaceMockRecorder struct {
	mock *MockCidPinnerInterface
}

// NewMockCidPinnerInterface creates a new mock instance.
func NewMockCidPinnerInterface(ctrl *gomock.Controller) *MockCidPinnerInterface {
	mock := &MockCidPinnerInterface{ctrl: ctrl}
	mock.recorder = &MockCidPinnerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCidPinnerInterface) EXPECT() *MockCidPinnerInterfaceMockRecorder {
	return m.recorder
}

// Pin mocks base method.
func (m *MockCidPinnerInterface) Pin(ctx context.Context, cid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pin", ctx, cid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pin indicates an expected call of Pin.
func (mr *MockCidPinnerInterfaceMockRecorder) Pin(ctx, cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pin", reflect.TypeOf((*MockCidPinnerInterface)(nil).Pin), ctx, cid)
}
