// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/collection_created_subscription_provider_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/collection_created_subscription_provider_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/collection_created_subscription_provider_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge_blockchain/abi"
	ethereum "github.com/ethereum/go-ethereum"
	gomock "go.uber.org/mock/gomock"
)

// MockCollectionCreatedSubscriptionProviderInterface is a mock of CollectionCreatedSubscriptionProviderInterface interface.
type MockCollectionCreatedSubscriptionProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionCreatedSubscriptionProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockCollectionCreatedSubscriptionProviderInterfaceMockRecorder is the mock recorder for MockCollectionCreatedSubscriptionProviderInterface.
type MockCollectionCreatedSubscriptionProviderInterfaceMockRecorder struct {
	mock *MockCollectionCreatedSubscriptionProviderInterface
}

// NewMockCollectionCreatedSubscriptionProviderInterface creates a new mock instance.
func NewMockCollectionCreatedSubscriptionProviderInterface(ctrl *gomock.Controller) *MockCollectionCreatedSubscriptionProviderInterface {
	mock := &MockCollectionCreatedSubscriptionProviderInterface{ctrl: ctrl}
	mock.recorder = &MockCollectionCreatedSubscriptionProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionCreatedSubscriptionProviderInterface) EXPECT() *MockCollectionCreatedSubscriptionProviderInterfaceMockRecorder {
	return m.recorder
}

// StartCollectionCreatedSubscription mocks base method.
func (m *MockCollectionCreatedSubscriptionProviderInterface) StartCollectionCreatedSubscription(ctx context.Context, chainId uint64) (<-chan *abi.AgentCollectionsManagerCollectionCreated, ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartCollectionCreatedSubscription", ctx, chainId)
	ret0, _ := ret[0].(<-chan *abi.AgentCollectionsManagerCollectionCreated)
	ret1, _ := ret[1].(ethereum.Subscription)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StartCollectionCreatedSubscription indicates an expected call of StartCollectionCreatedSubscription.
func (mr *MockCollectionCreatedSubscriptionProviderInterfaceMockRecorder) StartCollectionCreatedSubscription(ctx, chainId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartCollectionCreatedSubscription", reflect.TypeOf((*MockCollectionCreatedSubscriptionProviderInterface)(nil).StartCollectionCreatedSubscription), ctx, chainId)
}
