// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/ipfs_check_requester_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/ipfs_check_requester_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/ipfs_check_requester_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIpfsCheckRequesterInterface is a mock of IpfsCheckRequesterInterface interface.
type MockIpfsCheckRequesterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockIpfsCheckRequesterInterfaceMockRecorder
	isgomock struct{}
}

// MockIpfsCheckRequesterInterfaceMockRecorder is the mock recorder for MockIpfsCheckRequesterInterface.
type MockIpfsCheckRequesterInterfaceMockRecorder struct {
	mock *MockIpfsCheckRequesterInterface
}

// NewMockIpfsCheckRequesterInterface creates a new mock instance.
func NewMockIpfsCheckRequesterInterface(ctrl *gomock.Controller) *MockIpfsCheckRequesterInterface {
	mock := &MockIpfsCheckRequesterInterface{ctrl: ctrl}
	mock.recorder = &MockIpfsCheckRequesterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIpfsCheckRequesterInterface) EXPECT() *MockIpfsCheckRequesterInterfaceMockRecorder {
	return m.recorder
}

// GetHostNodeIds mocks base method.
func (m *MockIpfsCheckRequesterInterface) GetHostNodeIds(ctx context.Context, cid string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostNodeIds", ctx, cid)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostNodeIds indicates an expected call of GetHostNodeIds.
func (mr *MockIpfsCheckRequesterInterfaceMockRecorder) GetHostNodeIds(ctx, cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostNodeIds", reflect.TypeOf((*MockIpfsCheckRequesterInterface)(nil).GetHostNodeIds), ctx, cid)
}
