// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/minted_subscription_provider_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/minted_subscription_provider_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/minted_subscription_provider_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge_blockchain/abi"
	ethereum "github.com/ethereum/go-ethereum"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockMintedSubscriptionProviderInterface is a mock of MintedSubscriptionProviderInterface interface.
type MockMintedSubscriptionProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMintedSubscriptionProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockMintedSubscriptionProviderInterfaceMockRecorder is the mock recorder for MockMintedSubscriptionProviderInterface.
type MockMintedSubscriptionProviderInterfaceMockRecorder struct {
	mock *MockMintedSubscriptionProviderInterface
}

// NewMockMintedSubscriptionProviderInterface creates a new mock instance.
func NewMockMintedSubscriptionProviderInterface(ctrl *gomock.Controller) *MockMintedSubscriptionProviderInterface {
	mock := &MockMintedSubscriptionProviderInterface{ctrl: ctrl}
	mock.recorder = &MockMintedSubscriptionProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMintedSubscriptionProviderInterface) EXPECT() *MockMintedSubscriptionProviderInterfaceMockRecorder {
	return m.recorder
}

// StartMintedSubscription mocks base method.
func (m *MockMintedSubscriptionProviderInterface) StartMintedSubscription(ctx context.Context, chainId uint64, agentCollectionAddress common.Address) (<-chan *abi.AgentCollectionV1Minted, ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMintedSubscription", ctx, chainId, agentCollectionAddress)
	ret0, _ := ret[0].(<-chan *abi.AgentCollectionV1Minted)
	ret1, _ := ret[1].(ethereum.Subscription)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StartMintedSubscription indicates an expected call of StartMintedSubscription.
func (mr *MockMintedSubscriptionProviderInterfaceMockRecorder) StartMintedSubscription(ctx, chainId, agentCollectionAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMintedSubscription", reflect.TypeOf((*MockMintedSubscriptionProviderInterface)(nil).StartMintedSubscription), ctx, chainId, agentCollectionAddress)
}
