// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/mint_proposal_created_subscription_provider_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/mint_proposal_created_subscription_provider_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/mint_proposal_created_subscription_provider_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge_blockchain/abi"
	ethereum "github.com/ethereum/go-ethereum"
	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockMintProposalCreatedSubscriptionProviderInterface is a mock of MintProposalCreatedSubscriptionProviderInterface interface.
type MockMintProposalCreatedSubscriptionProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMintProposalCreatedSubscriptionProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockMintProposalCreatedSubscriptionProviderInterfaceMockRecorder is the mock recorder for MockMintProposalCreatedSubscriptionProviderInterface.
type MockMintProposalCreatedSubscriptionProviderInterfaceMockRecorder struct {
	mock *MockMintProposalCreatedSubscriptionProviderInterface
}

// NewMockMintProposalCreatedSubscriptionProviderInterface creates a new mock instance.
func NewMockMintProposalCreatedSubscriptionProviderInterface(ctrl *gomock.Controller) *MockMintProposalCreatedSubscriptionProviderInterface {
	mock := &MockMintProposalCreatedSubscriptionProviderInterface{ctrl: ctrl}
	mock.recorder = &MockMintProposalCreatedSubscriptionProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMintProposalCreatedSubscriptionProviderInterface) EXPECT() *MockMintProposalCreatedSubscriptionProviderInterfaceMockRecorder {
	return m.recorder
}

// StartMintProposalCreatedSubscription mocks base method.
func (m *MockMintProposalCreatedSubscriptionProviderInterface) StartMintProposalCreatedSubscription(ctx context.Context, chainId uint64, agentCollectionAddress common.Address) (<-chan *abi.AgentCollectionV1MintProposalCreated, ethereum.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartMintProposalCreatedSubscription", ctx, chainId, agentCollectionAddress)
	ret0, _ := ret[0].(<-chan *abi.AgentCollectionV1MintProposalCreated)
	ret1, _ := ret[1].(ethereum.Subscription)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StartMintProposalCreatedSubscription indicates an expected call of StartMintProposalCreatedSubscription.
func (mr *MockMintProposalCreatedSubscriptionProviderInterfaceMockRecorder) StartMintProposalCreatedSubscription(ctx, chainId, agentCollectionAddress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartMintProposalCreatedSubscription", reflect.TypeOf((*MockMintProposalCreatedSubscriptionProviderInterface)(nil).StartMintProposalCreatedSubscription), ctx, chainId, agentCollectionAddress)
}
