// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/minted_event_handler_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/minted_event_handler_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/minted_event_handler_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	reflect "reflect"

	abi "github.com/6022-labs/agentic-pinata-bridge/src/pinata_bridge_blockchain/abi"
	gomock "go.uber.org/mock/gomock"
)

// MockMintedEventHandlerInterface is a mock of MintedEventHandlerInterface interface.
type MockMintedEventHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMintedEventHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockMintedEventHandlerInterfaceMockRecorder is the mock recorder for MockMintedEventHandlerInterface.
type MockMintedEventHandlerInterfaceMockRecorder struct {
	mock *MockMintedEventHandlerInterface
}

// NewMockMintedEventHandlerInterface creates a new mock instance.
func NewMockMintedEventHandlerInterface(ctrl *gomock.Controller) *MockMintedEventHandlerInterface {
	mock := &MockMintedEventHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockMintedEventHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMintedEventHandlerInterface) EXPECT() *MockMintedEventHandlerInterfaceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockMintedEventHandlerInterface) Handle(ctx context.Context, chainId uint64, event *abi.AgentCollectionV1Minted) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, chainId, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockMintedEventHandlerInterfaceMockRecorder) Handle(ctx, chainId, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockMintedEventHandlerInterface)(nil).Handle), ctx, chainId, event)
}
