// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/mint_proposal_images_pinner_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/mint_proposal_images_pinner_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/mint_proposal_images_pinner_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	context "context"
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockMintProposalImagesPinnerInterface is a mock of MintProposalImagesPinnerInterface interface.
type MockMintProposalImagesPinnerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockMintProposalImagesPinnerInterfaceMockRecorder
	isgomock struct{}
}

// MockMintProposalImagesPinnerInterfaceMockRecorder is the mock recorder for MockMintProposalImagesPinnerInterface.
type MockMintProposalImagesPinnerInterfaceMockRecorder struct {
	mock *MockMintProposalImagesPinnerInterface
}

// NewMockMintProposalImagesPinnerInterface creates a new mock instance.
func NewMockMintProposalImagesPinnerInterface(ctrl *gomock.Controller) *MockMintProposalImagesPinnerInterface {
	mock := &MockMintProposalImagesPinnerInterface{ctrl: ctrl}
	mock.recorder = &MockMintProposalImagesPinnerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMintProposalImagesPinnerInterface) EXPECT() *MockMintProposalImagesPinnerInterfaceMockRecorder {
	return m.recorder
}

// Pin mocks base method.
func (m *MockMintProposalImagesPinnerInterface) Pin(ctx context.Context, chainId uint64, agentCollectionAddress common.Address, proposalId big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pin", ctx, chainId, agentCollectionAddress, proposalId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pin indicates an expected call of Pin.
func (mr *MockMintProposalImagesPinnerInterfaceMockRecorder) Pin(ctx, chainId, agentCollectionAddress, proposalId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pin", reflect.TypeOf((*MockMintProposalImagesPinnerInterface)(nil).Pin), ctx, chainId, agentCollectionAddress, proposalId)
}
