// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/pinata_requester_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/pinata_requester_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/pinata_requester_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPinataRequesterInterface is a mock of PinataRequesterInterface interface.
type MockPinataRequesterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPinataRequesterInterfaceMockRecorder
	isgomock struct{}
}

// MockPinataRequesterInterfaceMockRecorder is the mock recorder for MockPinataRequesterInterface.
type MockPinataRequesterInterfaceMockRecorder struct {
	mock *MockPinataRequesterInterface
}

// NewMockPinataRequesterInterface creates a new mock instance.
func NewMockPinataRequesterInterface(ctrl *gomock.Controller) *MockPinataRequesterInterface {
	mock := &MockPinataRequesterInterface{ctrl: ctrl}
	mock.recorder = &MockPinataRequesterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinataRequesterInterface) EXPECT() *MockPinataRequesterInterfaceMockRecorder {
	return m.recorder
}

// IsCidUploaded mocks base method.
func (m *MockPinataRequesterInterface) IsCidUploaded(cid string) (*bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCidUploaded", cid)
	ret0, _ := ret[0].(*bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCidUploaded indicates an expected call of IsCidUploaded.
func (mr *MockPinataRequesterInterfaceMockRecorder) IsCidUploaded(cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCidUploaded", reflect.TypeOf((*MockPinataRequesterInterface)(nil).IsCidUploaded), cid)
}

// PinCid mocks base method.
func (m *MockPinataRequesterInterface) PinCid(cid string, hostNodes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PinCid", cid, hostNodes)
	ret0, _ := ret[0].(error)
	return ret0
}

// PinCid indicates an expected call of PinCid.
func (mr *MockPinataRequesterInterfaceMockRecorder) PinCid(cid, hostNodes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PinCid", reflect.TypeOf((*MockPinataRequesterInterface)(nil).PinCid), cid, hostNodes)
}
