// Code generated by MockGen. DO NOT EDIT.
// Source: src/pinata_bridge/services/interfaces/push_agent_image_cid_to_pinata_interface.go
//
// Generated by this command:
//
//	mockgen -source=src/pinata_bridge/services/interfaces/push_agent_image_cid_to_pinata_interface.go -destination=tests/pinata_bridge_mocks/services_mocks/interfaces_mocks/push_agent_image_cid_to_pinata_mock.go -package=interfaces_mocks
//

// Package interfaces_mocks is a generated GoMock package.
package interfaces_mocks

import (
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	gomock "go.uber.org/mock/gomock"
)

// MockPushAgentImageCidToPinataInterface is a mock of PushAgentImageCidToPinataInterface interface.
type MockPushAgentImageCidToPinataInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPushAgentImageCidToPinataInterfaceMockRecorder
	isgomock struct{}
}

// MockPushAgentImageCidToPinataInterfaceMockRecorder is the mock recorder for MockPushAgentImageCidToPinataInterface.
type MockPushAgentImageCidToPinataInterfaceMockRecorder struct {
	mock *MockPushAgentImageCidToPinataInterface
}

// NewMockPushAgentImageCidToPinataInterface creates a new mock instance.
func NewMockPushAgentImageCidToPinataInterface(ctrl *gomock.Controller) *MockPushAgentImageCidToPinataInterface {
	mock := &MockPushAgentImageCidToPinataInterface{ctrl: ctrl}
	mock.recorder = &MockPushAgentImageCidToPinataInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPushAgentImageCidToPinataInterface) EXPECT() *MockPushAgentImageCidToPinataInterfaceMockRecorder {
	return m.recorder
}

// PushFromCid mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushFromCid(cid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushFromCid", cid)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushFromCid indicates an expected call of PushFromCid.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushFromCid(cid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushFromCid", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushFromCid), cid)
}

// PushImageOfAgentImageProposal mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushImageOfAgentImageProposal(chainId uint64, agentCollectionAddress common.Address, proposalId big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushImageOfAgentImageProposal", chainId, agentCollectionAddress, proposalId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushImageOfAgentImageProposal indicates an expected call of PushImageOfAgentImageProposal.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushImageOfAgentImageProposal(chainId, agentCollectionAddress, proposalId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushImageOfAgentImageProposal", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushImageOfAgentImageProposal), chainId, agentCollectionAddress, proposalId)
}

// PushImagesOfMintProposal mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushImagesOfMintProposal(chainId uint64, agentCollectionAddress common.Address, proposalId big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushImagesOfMintProposal", chainId, agentCollectionAddress, proposalId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushImagesOfMintProposal indicates an expected call of PushImagesOfMintProposal.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushImagesOfMintProposal(chainId, agentCollectionAddress, proposalId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushImagesOfMintProposal", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushImagesOfMintProposal), chainId, agentCollectionAddress, proposalId)
}

// PushMissingImageCids mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushMissingImageCids() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushMissingImageCids")
	ret0, _ := ret[0].(error)
	return ret0
}

// PushMissingImageCids indicates an expected call of PushMissingImageCids.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushMissingImageCids() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushMissingImageCids", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushMissingImageCids))
}

// PushMissingImagesOfAgent mocks base method.
func (m *MockPushAgentImageCidToPinataInterface) PushMissingImagesOfAgent(chainId uint64, agentCollectionAddress common.Address, agentCollectionTokenId big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushMissingImagesOfAgent", chainId, agentCollectionAddress, agentCollectionTokenId)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushMissingImagesOfAgent indicates an expected call of PushMissingImagesOfAgent.
func (mr *MockPushAgentImageCidToPinataInterfaceMockRecorder) PushMissingImagesOfAgent(chainId, agentCollectionAddress, agentCollectionTokenId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushMissingImagesOfAgent", reflect.TypeOf((*MockPushAgentImageCidToPinataInterface)(nil).PushMissingImagesOfAgent), chainId, agentCollectionAddress, agentCollectionTokenId)
}
